### PR TITLE
Wrapper and table fixes

### PR DESCRIPTION
**Pull request by ljoakim**
A few updates/fixes:
- Updated the cmor table (+ a fix in the updating script)
- Updated the wrapper script to always overwrite old files. If a previous job fails, it may leave broken files, this is an attempt to make sure those don't affect the next try.
- A small fix to have all processed variable names in the cmorlight log filename, not only the first variable in the list given on command line.

@gnikulin : The updated table has updates to the "postitive" attribute fora few variables, but only tier1 ones as far as I can see. But that means those variables are missing this information in the current ERA5 tier1 cmorized variables.

### CODE REVIEW

**Review by doblerone — COMMENTED** [review]
Looks good to me.
But I am not entirely sure whether the -O option as default solves the problems of broken intermediate files. It only enforces the overwriting of the final (post: input to cmor, cmor: output of cmor) files, so intermediate (*tmp) files can still be there and cause trouble.

**Comment by ljoakim** [comment]
> But I am not entirely sure whether the -O option as default solves the problems of broken intermediate files. It only enforces the overwriting of the final (post: input to cmor, cmor: output of cmor) files, so intermediate (*tmp) files can still be there and cause trouble.

Ok, so then tmp-files need to be removed manually. Would you prefer not having the `-O` flag at all? Or maybe as a option to the wrapper script?

**Comment by doblerone** [comment]
> > But I am not entirely sure whether the -O option as default solves the problems of broken intermediate files. It only enforces the overwriting of the final (post: input to cmor, cmor: output of cmor) files, so intermediate (*tmp) files can still be there and cause trouble.
> 
> Ok, so then tmp-files need to be removed manually. Would you prefer not having the `-O` flag at all? Or maybe as a option to the wrapper script?

I sometimes have used it as an option to either master_cmor or master_port. Thus having it as an option to the wrapper script would be nice, but not crucial. It just feels a bit saver to use -O instead of rm on already existing final files.

**Comment by gnikulin** [comment]
> @gnikulin : The updated table has updates to the "postitive" attribute fora few variables, but only tier1 ones as far as I can see. But that means those variables are missing this information in the current ERA5 tier1 cmorized variables.

Yes, the positive attribute was fixed for few variables in tier1 and we need to postprocess these variables but first quality control for all tier1 and tier2 variables. Some other issues may be found.

**Review by gnikulin — APPROVED** [review]

**Comment by ljoakim** [comment]
> > > But I am not entirely sure whether the -O option as default solves the problems of broken intermediate files. It only enforces the overwriting of the final (post: input to cmor, cmor: output of cmor) files, so intermediate (*tmp) files can still be there and cause trouble.
> > 
> > 
> > Ok, so then tmp-files need to be removed manually. Would you prefer not having the `-O` flag at all? Or maybe as a option to the wrapper script?
> 
> I sometimes have used it as an option to either master_cmor or master_port. Thus having it as an option to the wrapper script would be nice, but not crucial. It just feels a bit saver to use -O instead of rm on already existing final files.

Just to be clear, is there a problem with leaving the `-O` flag hardcoded for now in the wrapper-script? Or would it be ok to merge this PR as is?

**Comment by doblerone** [comment]
Fine with me :-)

**Pull request merged**
