### PR TITLE
Rename all grid mapping variables to 'crs'

### LINKED ISSUE #24: grid mapping variable = "crs" for all projections (Lambert_Conformal, Mercator, etc.)
We need:

- to rename the grid mapping variable from `Lambert_Conformal` to `crs`
- to change the variable attribute `grid_mapping` from `Lambert_Conformal` to `crs`

In general, it would be good to make the above changes for other projections, e.g.  if `Mercator` is used. 

@doblerone as I remember you use the polar stereographic projection for the Arctic region ?

### PR DESCRIPTION
**Pull request by ljoakim**
Closes #24.

### CODE REVIEW

**Comment by ljoakim** [comment]
I'm opening this draft PR while I'm working on this. There is one thing I need help with:

In the post stage in [here](https://github.com/HCLIMcom/HCLIM2CMOR/blob/3e7a3b1ba76b7742905729457d0f593d29b03161/src/hclim_post/mergemon.sh#L261) in `mergemon.sh`, there is a call to `ncap2` where `Lambert_Conformal` is hard coded. I'm not really familiar with the toolset provided with cdo/nco and don't know how to adapt this line to be able to take care of the different types of grid mappings. Can you help out @doblerone, @gnikulin?

**Comment by gnikulin** [comment]
It takes time to understand why `lon=lon;lat=lat;Lambert_Conformal=Lambert_Conformal` is needed in the ncap2 command. @doblerone, can we skip this part completely? If `lon`, `lat`and `Lambert_Conformal` are in the input file all they should be copied to the output file by ncap2 ?

**Comment by doblerone** [comment]
I need to look into this. It is in the first step, i.e. before cmorisation. We need to merge 14 files, holding one vertical layer each, into one file holding all layers (new CORDEX request of 3D fields). ncap2 is the only command line tool I am aware of that can do it. The lon=lon;lat=lat;Lambert_Conformal=Lambert_Conformal is needed as far as I can see, because we are defining a new 3D file, i.e. we can't use the -A (append) option.
Maybe we can skip lat, lon and Lambert_Comfomaal here and fix it later on during cmorisation. Or use cdo setgrid or ncks.
I'll have to test this.

**Comment by ljoakim** [comment]
Is it possible to inspect a file using any of the `cdo` toolbox commands to find out which crs variable name is used, if we limit it to looking for one of the four specified names? Then it could be put in an environment variable and used in the `ncap2` command (?)

**Comment by gnikulin** [comment]
> This is asssuming that the variables in the HCLIM output have the attribute "grid_mapping". I think they should always have that.

`grid_mapping` is always presented so such an approach should work. In general, it can be done only once for the first input file. I hope that we don't have simulations with two different projections :-).

**Comment by ljoakim** [comment]
I've added the line to `mergemon.sh`. It's in the loop, but it should be a quick operation, and at least it's only run once for every collection of 14 level files.

I'm currently test running a few cmorizations, including `tsl`. Assuming they all go through the code should be fine. But you're welcome to review it if you'd like.

**Comment by gnikulin** [comment]
it's fine from my side, only testing helps here :-)

**Review by gnikulin — APPROVED** [review]

**Review by doblerone — APPROVED** [review]

**Pull request merged**
