### PR TITLE
Added drs elements/attributes to simulation config (closes #17)

### LINKED ISSUE #17: add more DRS elements and some global attributes to simulation metadata in simulation_config.yml
Now we have a minimum number of the DRS elements (all "driving"-related ones) for each simulation in [simulation_config.yml](https://github.com/doblerone/HCLIM2CMOR/blob/master/config/simulation_config.yml) while others are hard-coded in [control_cmor_template.ini](https://github.com/doblerone/HCLIM2CMOR/blob/master/config/control_cmor_template.ini) 

it would be better to add more DRS elements and some global attributes that potentially can be different across the simulations (e.g.  domains, institutions, realizations) to [simulation_config.yml](https://github.com/doblerone/HCLIM2CMOR/blob/master/config/simulation_config.yml) instead of hard-coding them in [control_cmor_template.ini](https://github.com/doblerone/HCLIM2CMOR/blob/master/config/control_cmor_template.ini)

DRS elements:

`domain_id`
`institution_id`
`version_realization`
`source_id`  - assuming that can be different configurations, spectral nudging, etc.

Global attributes:

`domain`
`grid`
`contact`
`institution` if we include specific institutions that are responsible for generating and providing simulations, now it's _"The HARMONIE Climate Modelling Community (HCLIMcom)"_ while `institution_id` includes an identifier for the institution (need to think here)

### PR DESCRIPTION
**Pull request by ljoakim**
I've added the following drs elements / global attributes to the simulation config:
```
    domain: "Europe"
    domain_id: "EUR-12"
    grid: "Lambert conic conformal with 12.5 km grid spacing"
    institution: "The HARMONIE Climate Modelling Community (HCLIMcom)"
    institution_id: "HCLIMcom-SMHI"
    version_realisation: "v1-r1"
    source: "HARMONIE Climate Modelling Community (HCLIM-Com)"
    source_type: "ARCM"
    source_id: "HCLIM43-ALADIN"
    contact: "rossby@smhi.se"
```

- I've added what was mentioned in the issue (#17), plus `source` and `source_type`. The `grid` attribute replaces `native_resolution`, which I've removed.
- I have _not_ inspected the list of global attributes in `control_cmor_template.ini` to make sure it still matches the spec.

The PR is created as draft, to make sure all things are correct before merging.
- I know there are some values that should be changed, let me know which ones you want changed.
- I've added the same values to all simulations, is that correct?

### CODE REVIEW

**Comment by gnikulin** [comment]
Looks OK but I'll check in detail. We need first to register HCLIM43-ALADIN and all HCLIMcom institutions and then change values for some global attributes (e.g. institution_id and institution, for all NorESM2-MM driven runs `institution_id` should be "HCLIMcom-METNo" ). We also need to check mail address that will be used for contact at different institutions.

**Comment by doblerone** [comment]
Thanks, look OK to me as well. However, I am not entirely sure about source.
This should describe "#source: full model name/version and components (aerosol, atmos, land etc.)"
How about something like "HARMONIE Climate model cycle 43 with ALADIN physics". Maybe also add "with evolving aerosols" and "SURFEX land model"?

Considering the email address: We have registered cordex@met.no now.

**Comment by gnikulin** [comment]
I think "HARMONIE Climate model cycle 43 with ALADIN physics" looks fine. `source` (full model name/version) or `label_extended` in the registration form is defined as  "A longer description of the model name, possibly including the acronym expanded.". It's assumed that information about components should be provided via `further_info_url`  or any kind of RCM documentation.

**Comment by gnikulin** [comment]
Both HCLIMcom-SMHI and HCLIMcom-METNo have been registered and we need to use:

- `institution: "HARMONIE Climate Modelling Community (HCLIMcom) partner: Swedish Meteorological and Hydrological Institute (SMHI), Norrkoping, Sweden"` for all simulations generated at SMHI  and `institution: HARMONIE Climate Modelling Community (HCLIMcom) partner: Norwegian Meteorological Institute (METNo), Oslo, Norway"`for all simulations generated by METNo (202301, 202319, 202303)
- `contact: "rossby.cordex@smhi.se"` for SMHI and `cordex@met.no` for METNo
- `source: "HARMONIE Climate model cycle 43 with ALADIN physics"` for all simulations

**Comment by ljoakim** [comment]
I've updated the values, please have another look and make sure all is ok. Let me know if anything else needs to be updated.

I removed the draft status, so the PR can be merged if you think it is ready.

**Review by doblerone — APPROVED** [review]

**Pull request merged**
